# Generated by Django 4.2.30 on 2026-05-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL da Imagem')),
                ('purchase_link', models.URLField(max_length=500, verbose_name='Link de Compra')),
                ('price_range', models.CharField(blank=True, max_length=100, verbose_name='Faixa de Preço')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Comprado')),
                ('purchased_by', models.CharField(blank=True, max_length=200, verbose_name='Comprado por')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='Comprado em')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Presente',
                'verbose_name_plural': 'Presentes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
