# Generated by Django 4.2.30 on 2026-05-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do destinatário')),
                ('address_street', models.CharField(blank=True, max_length=300, verbose_name='Rua e número')),
                ('address_complement', models.CharField(blank=True, max_length=200, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=2, verbose_name='Estado (sigla)')),
                ('address_zip', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('pix_key', models.CharField(blank=True, help_text='CPF, e-mail, telefone ou chave aleatória', max_length=200, verbose_name='Chave PIX')),
                ('pix_qr_code', models.ImageField(blank=True, help_text='Upload da imagem do QR Code gerada pelo seu banco', null=True, upload_to='pix/', verbose_name='QR Code PIX')),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.RemoveField(
            model_name='gift',
            name='is_purchased',
        ),
        migrations.AddField(
            model_name='gift',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reservado em'),
        ),
        migrations.AddField(
            model_name='gift',
            name='reserved_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Reservado por'),
        ),
        migrations.AddField(
            model_name='gift',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('reserved', 'Reservado'), ('purchased', 'Comprado')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
