# Generated by Django 4.2.30 on 2026-05-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_siteconfig_remove_gift_is_purchased_gift_reserved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Loja')),
                ('logo', models.ImageField(blank=True, help_text='Upload da logomarca da loja (PNG transparente recomendado)', null=True, upload_to='stores/', verbose_name='Logomarca')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='Site da loja')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='gifts.store', verbose_name='Loja'),
        ),
    ]
